GET https://blog-api777.herokuapp.com/

###
GET https://blog-api777.herokuapp.com/posts

###
GET https://blog-api777.herokuapp.com/posts/A003

###

GET https://blog-api777.herokuapp.com/authors

###
POST https://blog-api777.herokuapp.com/posts
Content-Type: application/json

{
      "title": "title 2 ",
      "description": "post by author 4, this will send a mail to all other authors",
      "author": "A004"
}
###
POST https://blog-api777.herokuapp.com/authors
Content-Type: application/json

{
      "author_name": "random author",
      "author_email": "author@author.com"
}

###
PUT https://blog-api777.herokuapp.com/posts/P002
Content-Type: application/json

{
      "title": "Another random title",
      "description": "edited description",
      "author": "A002"
}

###

DELETE https://blog-api777.herokuapp.com/posts/P002
###

DELETE https://blog-api777.herokuapp.com/authors/A003

